### ISSUE TITLE
Add a README describing the project

### ISSUE THREAD

**Issue by Cotel** [infusionvlc/somnium_server#19]
✍️ 🤔

**Comment by tonilopezmr** [comment]
Most important issue

**Comment by tonilopezmr** [comment]
Add a section `How to launch the project` to explain how to launch it, how to access the Api docs, etc, etc...

**Comment by Cotel** [comment]
Yes, we should explain that. There are some resources on the Wiki but it's good to have these things on the README.

For now, if you want to run the project you have to launch `./gradlew bootRun` and the docs will be served on `http://localhost:8080/swagger-ui.html`
